### ISSUE TITLE
switch to a standard license?

### ISSUE THREAD

**Issue by stevengj** [coldfix/doc2md#3]
Though I appreciate the humorous disdain for legalese, it would be much better if you used a standard license text, written by people who understand copyright law and time-tested.  

For example, the [MIT/expat license](https://opensource.org/licenses/MIT) seem to be in the same spirit as the permission you want to grant.

One difficulty with an informal license is that any permission that is not *explicitly* granted is withheld by default in US copyright law; e.g. you say in your README that you grant permission to "copy and modify" the code, but you don't *explicitly* mention selling it (e.g. if it is incorporated in a commercial product).  Another difficulty in writing your own license is simply that everyone who wants to use/redistribute/... your code has to spend time and effort to figure our whether your license really grants the permissions they want.  If you use a familar, time-tested license, then people already know what it means.

**Comment by stevengj** [comment]
(I come from the scientific computation community, where there is long and bitter experience with people posting code online with informal, vague licenses.  Years later, people want to use the code but can't because the license terms aren't explicit enough or have unintended consequences, and by that point it has become hard to track down the original authors to see if they can relicense.)

**Comment by coldfix** [comment]
Thanks. I don't see how this license can be clearer or much easier to read, but I get your point. If you provide a pull request, I'll merge basically everything, since I don't care about this package.

**Comment by stevengj** [comment]
Thanks!
