### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'expandtabs'

### ISSUE THREAD

**Issue by Tagar** [coldfix/doc2md#5]
> $ python doc2md.py abalon.spark.sparkutils
> Traceback (most recent call last):
>   File "doc2md.py", line 310, in <module>
>     main()
>   File "doc2md.py", line 307, in main
>     print(doc2md(docstr, title, toc=args.toc))
>   File "doc2md.py", line 169, in doc2md
>     text = doctrim(docstr)
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/inspect.py", line 375, in cleandoc
>     lines = string.split(string.expandtabs(doc), '\n')
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/string.py", line 481, in expandtabs
>     return s.expandtabs(tabsize)
> AttributeError: 'NoneType' object has no attribute 'expandtabs'
> 

Thoughts?

**Comment by coldfix** [comment]
Module without docstring?
Module compiled with -OO?

Not sure, I don't use this module anymore and believe it was a mistake in the first place;)

**Comment by Tagar** [comment]
Thanks for the prompt response @coldfix 
I switched to https://github.com/NiklasRosenstein/pydoc-markdown/
it did a little better job on producing md output.
