### ISSUE TITLE
what is -a?

### ISSUE THREAD

**Issue by joseberlines** [coldfix/doc2md#8]
could you add explanation in readme as to what is -a and -non-tox?
might be obvious for an expert but not for a beginner

;-) 

thx.

**Comment by coldfix** [comment]
Hi, I haven't used this one in a long time so I can't tell you more than you will get from `doc2md --help`. `--no-toc` means do not create a table of contents. I would recommend you just try both options and see what effect they have on the generated document. Also, I'm not really maintaining this one anymore. If there is anyone who wants to take over, just let me know.
